import { WeatherIcon } from "../types/WeatherIcon";

export const weatherImages: WeatherIcon[] = [
    {id:1, url: '/weather/sunny.svg', text:'Sunny'},  
    {id:2, url: '/weather/sunny.svg', text:'Mostly Sunny'},
    {id:3, url: '/weather/sunny.svg', text:'Partly Sunny'},
    {id:4, url: '/weather/sunny.svg', text:'Intermittent Clouds'},
    {id:5, url: '/weather/sunny.svg', text:'Hazy Sunshine'},
    {id:6, url: '/weather/cloudy.svg', text:'Mostly Cloudy'},
    {id:7, url: '/weather/cloudy.svg', text:'Cloudy'},
    {id:8, url: '/weather/cloudy.svg', text:'Dreary (Overcast)'},
    {id:11, url: '/weather/rain.svg', text:'Fog'},
    {id:12, url: '/weather/rain.svg', text:'Showers'},
    {id:13, url: '/weather/rain.svg', text:'Mostly Cloudy w/ Showers'},
    {id:14, url: '/weather/rain.svg', text:'Partly Sunny w/ Showers'},
    {id:15, url: '/weather/rain.svg', text:'T-Storms'},
    {id:16, url: '/weather/rain.svg', text:'Mostly Cloudy w/ T-Storms'},
    {id:17, url: '/weather/rain.svg', text:'Partly Sunny w/ T-Storms'},
    {id:18, url: '/weather/rain.svg', text:'Rain'},
    {id:19, url: '/weather/rain.svg', text:'Flurries'},
    {id:20, url: '/weather/rain.svg', text:'Mostly Cloudy w/ Flurries'},
    {id:21, url: '/weather/rain.svg', text:'Partly Sunny w/ Flurries'},
    {id:22, url: '/weather/rain.svg', text:'Snow'},
    {id:23, url: '/weather/rain.svg', text:'Mostly Cloudy w/ Snow'},
    {id:24, url: '/weather/rain.svg', text:'Ice'},
    {id:25, url: '/weather/rain.svg', text:'Sleet'},
    {id:26, url: '/weather/rain.svg', text:'Freezing Rain'},
    {id:29, url: '/weather/rain.svg', text:'Rain and Snow'},
    {id:30, url: '/weather/rain.svg', text:'Hot'},
    {id:31, url: '/weather/rain.svg', text:'Cold'},
    {id:32, url: '/weather/rain.svg', text:'Windy'},
    {id:33, url: '/weather/rain.svg', text:'Clear'},
    {id:34, url: '/weather/rain.svg', text:'Mostly Clear'},
    {id:35, url: '/weather/rain.svg', text:'Partly Cloudy'},
    {id:36, url: '/weather/rain.svg', text:'Intermittent Clouds'},
    {id:37, url: '/weather/rain.svg', text:'Hazy Moonlight'},
    {id:38, url: '/weather/rain.svg', text:'Mostly Cloudy'},
    {id:39, url: '/weather/rain.svg', text:'Partly Cloudy w/ Showers'},
    {id:40, url: '/weather/rain.svg', text:'Mostly Cloudy w/ Showers'},
    {id:41, url: '/weather/rain.svg', text:'Partly Cloudy w/ T-Storms'},
    {id:42, url: '/weather/rain.svg', text:'Mostly Cloudy w/ T-Storms'},
    {id:43, url: '/weather/rain.svg', text:'Mostly Cloudy w/ Flurries'},
    {id:44, url: '/weather/rain.svg', text:'Mostly Cloudy w/ Snow'},
];

export const DEFAULT_WEATHER_ICON = {id:1, url: '/weather/sunny.svg', text:'Sunny'};